DATASETS:
  TYPE: "DAYTIME"

INPUT:
  IMAGE_SIZE: [64, 64]
  BATCH_SIZE: 32
  MAX_SEQ_LEN: 47

MODEL:
  LATENT_DIM: 128

NEPTUNE:
  USE: True

TRAIN:
  LR: 0.001
  EPOCHS: 500
  OPTIMIZER: "Adam"

SEED: 42
