DATASETS:
  TYPE: "NIGHT"

INPUT:
  IMAGE_SIZE: [64, 64]
  BATCH_SIZE: 32
  MAX_SEQ_LEN: 47

MODEL:
  LATENT_DIM: 128
  EVAL: True

TRAIN:
  LR: 0.001
  EPOCHS: 500
  OPTIMIZER: "Adam"

NEPTUNE: True
SEED: 42
